name: py36_screwframe
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.6
  - matplotlib=2.0.2
  - numpy=1.13.3
  - pandas=0.20.3
  - scipy=0.19.1
  - urllib3=1.22
  - nglview=1.0
  - biopandas
